/**
 * subido-app
 * Subi-dubi todo management application
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum FilterOperation {
    IN = 'IN',
    NOT_IN = 'NOT_IN',
    LIKE = 'LIKE',
    NOT_LIKE = 'NOT_LIKE',
    LT = 'LT',
    LE = 'LE',
    GT = 'GT',
    GE = 'GE',
    EQ = 'EQ',
    NOT_EQ = 'NOT_EQ',
    IS_NULL = 'IS_NULL',
    IS_NOT_NULL = 'IS_NOT_NULL'
};

