/**
 * subido-app
 * Subi-dubi todo management application
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldFilterDto } from './fieldFilterDto';
import { SortDto } from './sortDto';


export interface QueryRequestDto { 
    pageSize?: number;
    pageNumber?: number;
    sorts?: Array<SortDto>;
    fieldFilters?: Array<FieldFilterDto>;
}

