/**
 * subido-app
 * Subi-dubi todo management application
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sort } from './sort';
import { TodoItemDto } from './todoItemDto';


export interface QueryResponseDto { 
    todoItems: Array<TodoItemDto>;
    pageNumber: number;
    pageSize: number;
    totalPages: number;
    totalElements: number;
    sort?: Sort;
}

